version: '3'

services:
  login:
    container_name: credit-assignment
    build:
      context: .
      dockerfile: Dockerfile
    image: credit-assignment
    environment:
      PORT: 8080
    deploy:
      resources:
        limits:
          cpus: '.2'
          memory: 100M
        reservations:
          cpus: '.2'
          memory: 100M
    restart: always
    expose:
      - "8080"
    networks:
      - service-platform-nginx-network
networks:
  service-platform-nginx-network:
    external: true
